config/routes.rb
Rails.application.routes.draw do
  get 'rooms/index'
  get 'rooms/show'
  get 'book_comments/create'
  get 'book_comments/destroy'
  devise_for :users
  root to: "homes#top"
  get "/home/about"=>"homes#about"
  get '/search', to: 'searchs#search'

  resources :users, only: [:index,:show,:edit,:update] do
    get "daily_posts" => "users#daily_posts"
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member
    get :followers, on: :member
  end
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update]do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]

  # ゲストユーザーとしてログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :content, presence: true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: %i(destroy)

  def create
    book = Book.find(params[:book_id])
    @book_comment = current_user.book_comments.new(book_comment_params)
    unless @book_comment.save
      flash[:danger] = book_comment.errors
      redirect_back fallback_location: root_path
    end
    book_comments = Book.find(params[:book_id]).book_comments
  end

  def destroy
    @book = Book.find(params[:book_id])
    book_comment = BookComment.find(params[:id])
    book_comment.destroy
    @book_comments = Book.find(book_comment.book_id).book_comments
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:content).merge(book_id: params[:book_id])
  end

  def ensure_correct_user
    book_comment = BookComment.find(params[:id])
    return if book_comment.user_id == current_user.id
    flash[:danger] = '権限がありません'
    redirect_back fallback_location: root_path
  end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_comment.html.erb
<% book_comments.each do |book_comment| %>
  <tr>
    <td>
      <%= link_to user_path(book_comment.user) do %>
        <%= image_tag book_comment.user.get_profile_image, size:"80x80" %><br>
        <%= book_comment.user.name %>
      <% end %>
    </td>
    <td>
      <td><%= book_comment.content %></td>
    </td>
    <td>
      <% if book_comment.user_id == current_user.id %>
        <%= link_to "Destroy", book_book_comment_path(book_comment.book.id, book_comment.id), method: :delete, remote: true, class: "btn btn-danger pull-right" %>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/book_comments/create.js.erb
$("#book_<%= @book.id %> .comments-count").html("<%= @book.book_comments.count %>");
$("#comment").html("<%= j(render 'book_comments/comment', book_comments: @book_comments) %>");
$("#book_comment_content").val("");

app/views/book_comments/destroy.js.erb
$("#book_<%= @book.id %> .comments-count").html("<%= @book.book_comments.count %>");
$("#comment").html("<%= j(render 'book_comments/comment', book_comments: @book_comments) %>");